### ISSUE TITLE
Figure out Rubygems confusion of linux vs linux-musl

### ISSUE THREAD

**Issue by lloeki** [rubyjs/libv8-node#5]
`gem`/`bundle` wants to install `-linux-musl` when `Gem.platforms` actually has `-linux`.

**Comment by lloeki** [comment]
Figured out at build time.

Now need to figure out why gem/bundle install picks the wrong one.

**Comment by lloeki** [comment]
> Now need to figure out why gem/bundle install picks the wrong one.

Figured out: https://github.com/rubygems/rubygems/issues/3174

PR upstream here: https://github.com/rubygems/rubygems/pull/4082

**Comment by tisba** [comment]
@Ecco please reference issues if you are cross-posting. https://github.com/rubyjs/mini_racer/issues/231#issuecomment-1035600526

If somebody finds this one here, the workaround is to install via: `gem install libv8-node --version 16.10.0.0 --platform x86_64-linux-libc`.

**Comment by copiousfreetime** [comment]
Quick Note here - I updated  ruygems itself is at 3.3.24 and the msul/libc platform resolution appears to be working correctly for me on both on ubuntu 20 and 22.

`gem update --system` if you need that information too.

/c https://github.com/rubyjs/mini_racer/issues/231 and https://github.com/rubygems/rubygems/issues/5508

**Comment by tisba** [comment]
I think this can be closed, @lloeki

**Comment by lloeki** [comment]
True
